export default {
	HOST: 'http://localhost',
	SERVER: {
		// States
		STATE: {
			UNCONNECTED: 1,
			CONNECTING: 2,
			CONNECTED: 3,
			UNAUTHENTICATED: 4,
			CONNECTION_ERROR: 5,
			DISCONNECTED: 6
		},
		// Events
		EVENT: {
			CONNECTION_REQUEST: 1,
			CONNECTION_PENDING: 2,
			CONNECTION_SUCCESS: 3,
			CONNECTION_FAILURE: 4,
			AUTHENTICATION_FAILURE: 5,
			CONNECTION_LOST: 6,
			DATA_INIT: 7,
			DATA_TEXT: 8,
			ROOMS_INITIALIZED: 9,
			ROOM_UPDATE_REQUEST: 10,
			ROOM_UPDATED: 11,
			CREATE_ROOM: 12,
			ROOM_CREATED: 13,
			SELECT_ROOM: 14,
			ROOM_SELECTED: 15,
			ADD_PARTICIPANTS: 16,
			PARTICIPANTS_ADDED: 17,
			SEND_MESSAGE: 18,
			MESSAGE_SENT:19,
			EXIT_ROOM: 20,
			ROOM_EXITED: 21
		}
	}
}
